YourRandomActOfKindness/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("backend.urls")),
]

backend/urls.py
from django.urls import path

from . import views

app_name = 'backend'

urlpatterns = [
    path('', views.index, name='index'),
    path('faqs', views.faq, name='faq'),
    path('contact-us', views.Contact.as_view(), name='contact'),
    path('accounts/register', views.Register.as_view(), name='registration'),
    path('accounts/login', views.Login.as_view(), name='login'),
    path('accounts/logout', views.logout_view, name='logout'),
    path('rubies/donate', views.Rubies.as_view(), name='donate'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('active/campaigns', views.index, name='campaigns'),
    path('profile/update', views.index, name='update_profile'),
    path('checkout/<int:num>', views.checkout, name="checkout"),
]

backend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator

# Create your models here.
class User(AbstractUser):
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    contact = models.CharField(max_length=10, validators=[MinLengthValidator(10)], null=True, blank=False)
    contrib = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Category(models.Model):
    name = models.TextField()
    priority = models.IntegerField(default=0)

class Organisation(models.Model):
    name = models.TextField()
    registrant = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    video = models.FileField(upload_to='audio/')

    class Meta:
        db_table = 'Audio_store'

    def __str__(self):
        return self.name

class Campaign(models.Model):
    org = models.ForeignKey(Organisation, null=True, blank=False, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, blank=False, on_delete=models.CASCADE)
    start = models.DateTimeField(auto_now_add=True)
    requirement = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    name = models.TextField()
    description = models.TextField()
    blog = models.TextField()

    def __str__(self):
        return self.name

class Ruby(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    campaign = models.ForeignKey(Campaign, on_delete=models.SET_NULL, null=True, blank=False)
    date = models.DateTimeField(auto_now_add=True)

class Queue(models.Model):
    name = models.CharField(max_length=2, default="p1")
    priority = models.IntegerField(default=0, blank=False, unique=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    process = models.ForeignKey(Campaign, null=True, blank=False, on_delete=models.CASCADE)
    queue = models.ForeignKey(Queue, null=True, blank=False, on_delete=models.CASCADE)
    id = models.IntegerField(primary_key=True)
    quantum = models.IntegerField(default=4)

class State(models.Model):
    cur = models.ForeignKey(Item, null=True, blank=True, on_delete=models.CASCADE)
    funds = models.IntegerField(default=0)

class ContactUs(models.Model):
    From = models.TextField()
    subject = models.TextField()
    message = models.TextField()
    email = models.TextField()

backend/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .models import Queue, State, ContactUs, Item, Campaign, Organisation, User, Category, Ruby
from django.contrib.auth import login, logout, authenticate

# Create your views here.
def index(request):
    return render(request, 'backend/index.html')

def stream_file(request, pk):
    instance = get_object_or_404(Campaign, id=pk)
    response = HttpResponse()
    response['Content-Type'] = instance.content_type
    response['Content-Length'] = len(instance.picture)
    response.write(instance.picture)
    return response

def profile(request, pk):
    user = User.objects.get(id=pk)
    return render(request, "backend/profile.html", {
        "user": user,
    })

class Register(View):
    template = 'backend/register.html'
    success_url = 'backend:profile'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        contact = request.POST["contact"]
        email = request.POST["email"]
        p1 = request.POST["p1"]
        p2 = request.POST["p2"]

        if not p1 == p2:
            return render(request, self.template, {
                'message': "passwords don't match",
            })

        if not p1 or not p2 or not first_name or not last_name or not contact or not email:
            return render(request, self.template, {
                'message': "Please enter all fields",
            })

        try:
            user = User.objects.create(first_name=first_name, last_name=last_name, email=email, username=email, password=p1)
            user.save()
        except:
            return render(request, self.template, {
                'message': "User with these credentials already exists",
            })
        login(request, user)

        return HttpResponseRedirect(reverse(self.success_url, kwargs={'pk':user.id, }))

class Login(View):
    template = 'backend/login.html'
    success_url = 'backend:index'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        if not username or not password:
            return render(request, self.template, {
                'message': "Please enter all fields",
            })

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
        else:
            return render(request, self.template, {
                "message": "Invalid username and/or password."
            })

        return HttpResponseRedirect(reverse(self.success_url))

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("backend:index"))

def faq(request):
    return render(request, "backend/faq.html")

class Contact(View):
    template = 'backend/contact-us.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        From = request.POST['name']
        message = request.POST['message']
        email = request.POST['email']
        subject = request.POST['subject']

        instance = ContactUs.objects.create(From=From, message=message, email=email, subject=subject)
        instance.save()

        return render(request, self.template, {
            "message": "Thank You, we got your message and will get back to you."
        })

def checkout(request, num):
    return render(request, "backend/checkout.html", {
        'num': num,
        'total': 5 * num,
    })

class Rubies(View):
    template = "backend/buy_rubies.html"
    success_url = "backend:checkout"

    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("backend:registration"))
        return render(request, self.template)

    def post(self, request):
        num = request.POST['num']
        return HttpResponseRedirect(reverse(self.success_url, kwargs={'num':num, }))

backend/templates/backend/buy_rubies.html
{% extends 'layout.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  Donate
{% endblock %}

{% block main %}
  <main class="page pricing-table-page">
      <section class="text-light bg-dark clean-block clean-pricing dark">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Buy the world some Rubies...</h2>
                  <p>All the transactions happen through Rubies! The Money you donate on this website will be added to the pool from which campaigns will get their share, and for that you will have to buy rubies, each of which is individually traceable, so you know what's being done with your money...</p>
              </div>
              <div class="row justify-content-center">
                  <div class="col-md-5 col-lg-4">
                      <div class="bg-secondary border-warning shadow-lg clean-pricing-item">
                          <div class="heading">
                              <h3>Cost</h3>
                          </div>
                          <p><i class="icon-diamond icon"></i></p>
                          <div class="features">
                              <h4><span class="feature">Bought On:&nbsp;</span><span>Date</span></h4>
                          </div>
                          <div class="price">
                              <h4>$5 for one</h4>
                          </div>
                          <section class="bg-dark clean-block clean-form dark">
                              <div class="container bg-dark bg-gradient shadow-lg">
                                  <div class="block-heading">
                                      <p>How Many would you like to donate?</p>
                                  </div>
                                  <form class="bg-secondary border-warning shadow-lg" method="post" action="{% url 'backend:donate' %}" id="f1">
                                    {% csrf_token %}
                                      <div class="mb-3">
                                          {{ form | crispy }}
                                      </div>
                                  </form>
                              </div>
                          </section><button class="btn btn-primary d-block w-100" type="submit" form="f1">Donate</button>
                      </div>
                  </div>
              </div>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/campaigns.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Campaigns
{% endblock %}

{% block main %}
  <main class="page blog-post-list">
      <section class="text-light bg-dark border-warning shadow-lg clean-block clean-blog-list dark">
          <div class="container">
              <div class="block-heading">
                  <div class="clean-block add-on newsletter-sign-up"><input type="text" class="form-control" placeholder="Email"><button class="btn btn-outline-primary" type="button">Search</button></div>
                  <h2 class="text-info">Active Campaigns</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
              </div>
              {% for c in campaigns %}
                <div class="text-light bg-dark bg-gradient border-warning shadow-lg block-content">
                    <div class="clean-blog-post">
                        <div class="row">
                            <div class="col-lg-5"><img class="rounded img-fluid" src="{% url 'backend:logo' c.id %}"></div>
                            <div class="col-lg-7">
                                <h3>{{ c.title }}</h3>
                                <div class="info"><span class="text-muted">{{ c.title }} by&nbsp;<a href="#">{{ c.organisation.registrant.first_name }} {{ c.organisation.registrant.last_name }}</a></span></div>
                                <p>{{ c.description }}</p><a href="{% url 'backend:campaign' c.id %}"><button class="btn btn-outline-primary btn-sm" type="button">Read More</button></a>
                            </div>
                        </div>
                    </div>
                </div>
              {% endfor %}
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/checkout.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Proceed
{% endblock %}

{% block main %}
  <main class="page payment-page">
      <section class="text-light bg-dark clean-block payment-form dark">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Payment</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
              </div>
              <form>
                  <div class="bg-dark border-warning shadow-lg products">
                      <h3 class="title">Checkout</h3>
                      <div class="item"><span class="price">$5</span>
                          <p class="item-name">Cost of one Ruby</p>
                      </div>
                      <div class="item"><span class="price">${{ num }}</span>
                          <p class="item-name">Quantity</p>
                          <p class="item-description">Fixed value per Quantity</p>
                      </div>
                      <div class="total"><span>Total</span><span class="price">${{ total }}</span></div>
                  </div>
                  <!--
                  <div class="bg-dark bg-gradient border-success card-details">
                      <h3 class="title">Card Details</h3>
                      <div class="row">
                          <div class="col-sm-7">
                              <div class="mb-3"><label class="form-label" for="card_holder">Card Holder</label><input class="form-control" type="text" id="card_holder" placeholder="Card Holder" name="card_holder"></div>
                          </div>
                          <div class="col-sm-5">
                              <div class="mb-3"><label class="form-label">Expiration date</label>
                                  <div class="input-group expiration-date"><input class="form-control" type="text" placeholder="MM" name="expiration_month"><input class="form-control" type="text" placeholder="YY" name="expiration_year"></div>
                              </div>
                          </div>
                          <div class="col-sm-8">
                              <div class="mb-3"><label class="form-label" for="card_number">Card Number</label><input class="form-control" type="text" id="card_number" placeholder="Card Number" name="card_number"></div>
                          </div>
                          <div class="col-sm-4">
                              <div class="mb-3"><label class="form-label" for="cvc">CVC</label><input class="form-control" type="text" id="cvc" placeholder="CVC" name="cvc"></div>
                          </div>
                          <div class="col-sm-12">
                              <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Proceed</button></div>
                          </div>
                      </div>
                  </div>
                  -->
              </form>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/contact-us.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Contact Us
{% endblock %}

{% block main %}
  <main class="page contact-us-page">
      <section class="text-light bg-dark border-dark clean-block clean-form dark">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Contact Us</h2>
                  <p>Submit an application or ask a query.</p>
              </div>
              <form class="bg-dark bg-gradient border-warning shadow-lg" action="{% url 'backend:contact' %}" method="post">
                {% csrf_token %}
                <br>
                {{ message }}
                <br>
                  <div class="mb-3"><label class="form-label" for="name">Name</label><input class="form-control" type="text" id="name" name="name"></div>
                  <div class="mb-3"><label class="form-label" for="subject">Subject</label><input class="form-control" type="text" id="subject" name="subject"></div>
                  <div class="mb-3"><label class="form-label" for="email">Email</label><input class="form-control" type="email" id="email" name="email"></div>
                  <div class="mb-3"><label class="form-label" for="message">Message</label><textarea class="form-control" id="message" name="message"></textarea></div>
                  <div class="mb-3"><input class="btn btn-primary" type="submit" value="Send"/></div>
              </form>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/faq.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  FAQs
{% endblock %}

{% block main %}
  <main class="page faq-page">
      <section class="text-light bg-dark border-warning shadow-lg clean-block clean-faq dark">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">FAQ</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
              </div>
              <div class="text-white bg-dark bg-gradient block-content">
                  <div class="faq-item">
                      <h4 class="question">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
                      <div class="answer">
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                  </div>
                  <div class="faq-item">
                      <h4 class="question">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
                      <div class="answer">
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
                      </div>
                  </div>
                  <div class="faq-item">
                      <h4 class="question">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
                      <div class="answer">
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                      </div>
                  </div>
              </div>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/index.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  HOME
{% endblock %}

{% block main %}
  <main class="text-dark page landing-page">
      <section class="text-black-50 clean-block clean-hero" style="background-image:url({% static 'img/tech/image4.jpg' %});color:rgba(9, 162, 255, 0.85);">
          <div class="text">
              <h2 class="text-light border-light shadow-lg">Your Random Act Of Kindness...</h2>
              <p class="border-light shadow-lg">Fund Non-Profit Organizations without having to select a single one! </p><button class="btn btn-outline-light btn-lg" type="button">Learn More</button>
          </div>
      </section>
      <section class="text-light bg-dark bg-gradient border-light shadow-lg clean-block clean-info dark">
          <div class="container">
              <div class="text-dark block-heading">
                  <h2 class="text-info">Info</h2>
                  <p class="text-light">YRAK is a platform which lets people donate money in terms of a digital currency called Ruby which has a fixed value ($5 for now). All someone who wishes to contribute has to do is, buy some rubies, even one can do!.</p>
              </div>
              <div class="row align-items-center">
                  <div class="col-md-6"><img class="img-thumbnail" src="{% static 'img/scenery/image5.jpg' %}"></div>
                  <div class="col-md-6">
                      <h3>What happens with the rubies??</h3>
                      <div class="getting-started-info">
                          <p>The money from that transaction is sent to the pool of money and an algorithm inspired from multilevel queue scheduling algorithms used by operating systems distributes funds to different campaigns registered by non-profit and humanitarian organizations..</p>
                      </div><button class="btn btn-outline-primary btn-lg" type="button">Join Now</button>
                  </div>
              </div>
          </div>
      </section>
      <section class="text-light bg-dark border-warning shadow-lg clean-block features">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Features</h2>
                  <p>Do your little part for the society...</p>
              </div>
              <div class="row justify-content-center">
                  <div class="col-md-5 feature-box"><i class="icon-globe icon"></i>
                      <h4>For Everyone</h4>
                      <p>Contributors, donors and workers all alike are welcome</p>
                  </div>
                  <div class="col-md-5 feature-box"><i class="icon-diamond icon"></i>
                      <h4>Transparancy</h4>
                      <p>See what happens with every ruby you bought</p>
                  </div>
                  <div class="col-md-5 feature-box"><i class="icon-screen-smartphone icon"></i>
                      <h4>Connect</h4>
                      <p>Connect with many global organizations</p>
                  </div>
                  <div class="col-md-5 feature-box"><i class="icon-refresh icon"></i>
                      <h4>Take Part</h4>
                      <p>Contact us and start a campaign yourself!!</p>
                  </div>
              </div>
          </div>
      </section>
      <section class="text-light bg-dark bg-gradient border-light shadow-lg clean-block about-us">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Why sign up..</h2>
                  <p>Let's all come together and work for a better future</p>
              </div>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/login.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Login
{% endblock %}

{% block main %}
  <main class="page login-page">
      <section class="text-light bg-dark clean-block clean-form dark">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Log In</h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
              </div>
              <form class="bg-dark bg-gradient border-warning shadow-lg" method="post" action="{% url 'backend:login' %}">
                {% csrf_token %}
                  <div class="mb-3"><label class="form-label" for="email">Email</label><input class="form-control item" type="email" id="email" name="username"></div>
                  <div class="mb-3"><label class="form-label" for="password">Password</label><input class="form-control" type="password" id="password" name="password"></div>
                  <div class="mb-3"></div><input class="btn btn-primary" type="submit" value="Log In" />
                  <br>
                  {{ message }}
              </form>
          </div>
      </section>
  </main>
{% endblock %}

backend/templates/backend/profile.html
{% extends 'layout.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}
  {{ request.user.first_name }}
{% endblock %}

{% block main %}
  <main class="page">
      <section class="text-light bg-dark shadow-lg clean-block about-us">
          <div class="container">
              <div class="block-heading">
                  <h2 class="text-info">Profile</h2>
                  <p>Contributor, Member Since - {{ user.created_at }}</p>
              </div>
              <div class="row justify-content-center">
                  <div class="col-sm-6 col-lg-4">
                      <div class="card text-center clean-card"><img class="card-img-top w-100 d-block" src="assets/img/avatars/avatar2.jpg">
                          <div class="card-body bg-dark bg-gradient shadow-lg info">
                              <p class="card-text">{{ user.first_name }} {{ user.last_name }}</p>
                              <div class="icons"><a href="#"><i class="icon-social-facebook"></i></a><a href="#"><i class="icon-social-instagram"></i></a><a href="#"><i class="icon-social-twitter"></i></a></div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <section class="clean-block features">
              <div class="container">
                  <div class="row justify-content-center">
                      <div class="col-md-5 feature-box"><i class="icon-diamond icon"></i>
                          <h4>Contributions made - {{ user.contrib }}</h4>
                      </div>
                  </div>
              </div>
          </section>
          <section class="bg-dark border-warning shadow-lg clean-block clean-form dark">
              <div class="container">
                  <div class="block-heading">
                      <h2 class="text-info">Update Profile</h2>
                  </div>
                  <form class="bg-dark bg-gradient border-warning shadow-lg" method="post" action="{% url 'backend:update_profile' %}">
                    {% csrf_token %}
                      <div class="mb-3">
                          {{ form | crispy }}
                      </div><input class="btn btn-primary" type="submit" value="Update Profile"/>
                  </form>
              </div>
          </section>
      </section>
  </main>
{% endblock %}

backend/templates/backend/register.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}
  Register
{% endblock %}

{% block main %}
  <main class="page registration-page">
        <section class="text-light bg-dark clean-block clean-form dark">
            <div class="container">
                <div class="block-heading">
                    <h2 class="text-info">Registration</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
                </div>
                <form class="bg-dark bg-gradient border-warning shadow-lg" action="{% url 'backend:registration' %}" method="post">
                  {% csrf_token %}
                    <div class="mb-3"><label class="form-label" for="name">First Name</label><input class="form-control item" type="text" id="name" name="first_name"></div>
                    <div class="mb-3"><label class="form-label" for="name">Last Name</label><input class="form-control item" type="text" id="name" name="last_name"></div>
                    <div class="mb-3"><label class="form-label" for="name">Contact</label><input class="form-control item" type="text" id="name" name="contact"></div>
                    <div class="mb-3"><label class="form-label" for="email">Email</label><input class="form-control item" type="email" id="email" name="email"></div>
                    <div class="mb-3"><label class="form-label" for="password">Password</label><input class="form-control item" type="password" id="password" name="p1"></div><label class="form-label" for="password">Confirm Password</label><input class="form-control item" type="password" id="password-1" name='p2'>
                    <input class="btn btn-primary" type="submit" value="Sign Up" />
                    <br>
                    {{ message }}
                    Already have an account, <a href="{% url 'backend:login' %}">Login here.</a>
                </form>
            </div>
        </section>
    </main>
{% endblock %}

backend/templates/layout.html
<!DOCTYPE html>

{% load static %}

<html class="text-dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="{% static 'css/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/vanilla-zoom.min.css' %}">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top textwhite bg-success text-white clean-navbar">
        <div class="container"><a class="navbar-brand link-light logo" href="{% url 'backend:index' %}">Home</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse text-light" id="navcol-1">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'backend:faq' %}">FAQs</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'backend:donate' %}">Donate</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'backend:contact' %}">Contact Us</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'backend:campaigns' %}">Campaigns</a></li>
                    {% if request.user.is_authenticated %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'backend:profile' request.user.id %}">Profile</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url 'backend:logout' %}">Logout</a></li>
                    {% else %}
                      <li class="nav-item"><a class="nav-link" href="{% url 'backend:registration' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block main %}

    {% endblock %}
    <footer class="bg-dark bg-gradient page-footer dark"></footer>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{% static 'js/vanilla-zoom.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>

</html>